# Generated by Django 5.0.3 on 2024-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_last_name_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_picture/%Y/%m/%d/'),
        ),
    ]
