# Generated by Django 5.0.3 on 2024-03-09 21:30

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('Soft_delete', django.db.models.manager.Manager()),
            ],
        ),
    ]
