# Generated by Django 5.0.3 on 2024-03-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='profile',
            index_together=set(),
        ),
    ]
