# Generated by Django 5.0.3 on 2024-03-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(upload_to='post_picture/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
