# Generated by Django 5.0.3 on 2024-03-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_managers_alter_profile_unique_together_and_more'),
        ('post', '0003_alter_post_post_picture_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='owner_slug_unique',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='title',
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='owner_slug_unique'),
        ),
    ]
