# Generated by Django 5.0.3 on 2024-03-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_comment_owner_post_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comments',
        ),
    ]
