# Generated by Django 5.0.3 on 2024-03-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_owner_post_comments',
        ),
    ]
