# Generated by Django 5.0.3 on 2024-03-28 18:53

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('post', '0002_image_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='post.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.fields.NullBooleanField, related_name='posts', to='account.profile'),
        ),
    ]
