# Generated by Django 5.0.3 on 2024-03-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_image_post_image_alter_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to='profile_picture/%Y/%m/%d/'),
        ),
    ]
