# Generated by Django 5.0.3 on 2024-03-28 19:53

import app.core.mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(upload_to=app.core.mixin.image_upload_path_mixin),
        ),
    ]
