# Generated by Django 5.0.3 on 2024-03-31 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_commentlike'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_post_imagee__images',
        ),
    ]
